/**
 * Pi (earendil-works/pi-coding-agent) has no MCP client: its model only sees built-in tools and
 * tools that extensions register through `pi.registerTool`. Resin therefore installs a small,
 * Resin-owned extension file that speaks MCP over stdio to `resin mcp` and registers each learned
 * gateway tool as a Pi tool named `mcp__<server>__<tool>`. The extension follows
 * `notifications/tools/list_changed`, so learned tools reach the model without a Pi restart.
 * The gateway's discovery meta-tools are not registered: Pi sends every tool definition with
 * every request, and a client that registers learned tools directly never needs them.
 */

/** First line of every extension Resin writes; uninstall only deletes files that carry it. */
export const PI_RESIN_EXTENSION_MARKER = "// resin-managed: pi-mcp-bridge";

/** File name of the Resin extension inside `<agent-dir>/extensions/`. */
export const PI_RESIN_EXTENSION_FILE_NAME = "resin.ts";

/** Prefix of Pi tool names that front MCP tools registered by the Resin bridge extension. */
export const PI_MCP_TOOL_PREFIX = "mcp__";

/**
 * Gateway meta-tools the bridge does not register. They exist for clients whose native catalog
 * can go stale; the bridge follows list_changed, so they would only add per-request tokens.
 */
export const PI_BRIDGE_HIDDEN_TOOLS = [
  "search_tools",
  "get_tool_schema",
  "invoke_tool",
  "manage_tools",
] as const;

export interface PiMcpBridgeServer {
  /** MCP server name; becomes the `mcp__<name>__` tool-name segment. */
  name: string;
  command: string;
  args: readonly string[];
  env?: Record<string, string>;
}

/**
 * Pi tool name for an MCP tool. Provider tool names must match `^[A-Za-z0-9_-]{1,64}$`, so other
 * characters become `_` and the result is truncated to 64 characters.
 */
export function piMcpToolName(serverName: string, toolName: string): string {
  const sanitize = (value: string) => value.replace(/[^A-Za-z0-9_-]/g, "_");
  return `${PI_MCP_TOOL_PREFIX}${sanitize(serverName)}__${sanitize(toolName)}`.slice(0, 64);
}

/**
 * Splits a Pi tool name produced by {@link piMcpToolName} into server and tool segments.
 * Returns null for built-in and other extension tools.
 */
export function parsePiMcpToolName(name: string): { server: string; tool: string } | null {
  if (!name.startsWith(PI_MCP_TOOL_PREFIX)) {
    return null;
  }
  const rest = name.slice(PI_MCP_TOOL_PREFIX.length);
  const separator = rest.indexOf("__");
  if (separator <= 0 || separator + 2 >= rest.length) {
    return null;
  }
  return { server: rest.slice(0, separator), tool: rest.slice(separator + 2) };
}

/**
 * Renders the extension source. The output is plain JavaScript that is also valid TypeScript,
 * because Pi loads `.ts` extensions through jiti without a project tsconfig.
 */
export function renderPiResinExtension(server: PiMcpBridgeServer): string {
  const config = JSON.stringify(
    { name: server.name, command: server.command, args: [...server.args], env: server.env ?? {} },
    null,
    2,
  );
  return `${PI_RESIN_EXTENSION_MARKER}
// Generated by Resin. Do not edit: \`resin init\` rewrites this file and \`resin uninstall\` deletes it.
// Pi has no MCP client, so this extension connects to Resin's MCP gateway over stdio and exposes
// its tools to the model as Pi tools named mcp__<server>__<tool>.
import { spawn } from "node:child_process";

const SERVER = ${config};
const HIDDEN_TOOLS = ${JSON.stringify(PI_BRIDGE_HIDDEN_TOOLS)};
const CONNECT_TIMEOUT_MS = 20000;
const PROTOCOL_VERSION = "2025-06-18";

function sanitize(value) {
  return String(value).replace(/[^A-Za-z0-9_-]/g, "_");
}

function piToolName(toolName) {
  return ("${PI_MCP_TOOL_PREFIX}" + sanitize(SERVER.name) + "__" + sanitize(toolName)).slice(0, 64);
}

function createClient(cwd, onToolsChanged) {
  const child = spawn(SERVER.command, SERVER.args, {
    cwd,
    env: { ...process.env, ...SERVER.env },
    stdio: ["pipe", "pipe", "ignore"],
  });
  const pending = new Map();
  let nextId = 1;
  let buffer = "";
  let closed = false;

  const failAll = (error) => {
    closed = true;
    for (const entry of pending.values()) entry.reject(error);
    pending.clear();
  };
  child.on("error", (error) => failAll(error));
  child.on("exit", (code, signal) => failAll(new Error(SERVER.name + " MCP server exited (" + (signal || code) + ")")));
  child.stdout.setEncoding("utf8");
  child.stdout.on("data", (chunk) => {
    buffer += chunk;
    let newline = buffer.indexOf("\\n");
    while (newline !== -1) {
      const line = buffer.slice(0, newline).trim();
      buffer = buffer.slice(newline + 1);
      newline = buffer.indexOf("\\n");
      if (!line) continue;
      let message;
      try {
        message = JSON.parse(line);
      } catch {
        continue;
      }
      if (message.id !== undefined && pending.has(message.id) && message.method === undefined) {
        const entry = pending.get(message.id);
        pending.delete(message.id);
        if (message.error) entry.reject(new Error(message.error.message || "MCP error " + message.error.code));
        else entry.resolve(message.result);
      } else if (message.method === "notifications/tools/list_changed") {
        onToolsChanged();
      } else if (message.method !== undefined && message.id !== undefined) {
        send({ jsonrpc: "2.0", id: message.id, error: { code: -32601, message: "Method not found" } });
      }
    }
  });

  function send(message) {
    if (closed) return;
    child.stdin.write(JSON.stringify(message) + "\\n");
  }

  function request(method, params, signal) {
    if (closed) return Promise.reject(new Error(SERVER.name + " MCP server is not running"));
    const id = nextId++;
    const { promise, resolve, reject } = Promise.withResolvers();
    const onAbort = () => {
      pending.delete(id);
      send({ jsonrpc: "2.0", method: "notifications/cancelled", params: { requestId: id, reason: "aborted" } });
      reject(new Error("Aborted"));
    };
    if (signal?.aborted) {
      onAbort();
      return promise;
    }
    signal?.addEventListener("abort", onAbort, { once: true });
    pending.set(id, {
      resolve: (value) => {
        signal?.removeEventListener("abort", onAbort);
        resolve(value);
      },
      reject: (error) => {
        signal?.removeEventListener("abort", onAbort);
        reject(error);
      },
    });
    send({ jsonrpc: "2.0", id, method, params });
    return promise;
  }

  return {
    request,
    notify: (method, params) => send({ jsonrpc: "2.0", method, params }),
    close() {
      if (closed) return;
      closed = true;
      child.stdin.end();
      child.kill();
    },
  };
}

function toPiContent(result) {
  const content = [];
  for (const part of result?.content ?? []) {
    if (part.type === "text") content.push({ type: "text", text: part.text });
    else if (part.type === "image") content.push({ type: "image", data: part.data, mimeType: part.mimeType });
    else content.push({ type: "text", text: JSON.stringify(part) });
  }
  if (content.length === 0 && result?.structuredContent !== undefined) {
    content.push({ type: "text", text: JSON.stringify(result.structuredContent) });
  }
  return content;
}

function withTimeout(promise, ms, label) {
  const timeout = Promise.withResolvers();
  const timer = setTimeout(() => timeout.reject(new Error(label + " timed out after " + ms + "ms")), ms);
  return Promise.race([promise, timeout.promise]).finally(() => clearTimeout(timer));
}

export default function resinMcpBridge(pi) {
  let client = null;
  const registered = new Map();

  async function listTools() {
    const tools = [];
    let cursor;
    do {
      const page = await client.request("tools/list", cursor ? { cursor } : {});
      tools.push(...(page?.tools ?? []));
      cursor = page?.nextCursor;
    } while (cursor);
    return tools;
  }

  function registerMcpTool(tool) {
    const name = piToolName(tool.name);
    pi.registerTool({
      name,
      label: tool.title || tool.name,
      description: tool.description || tool.name,
      promptSnippet: (tool.description || tool.name).split("\\n")[0],
      parameters: tool.inputSchema || { type: "object", properties: {} },
      async execute(_toolCallId, params, signal) {
        if (!client) throw new Error(SERVER.name + " MCP server is not connected");
        const result = await client.request("tools/call", { name: tool.name, arguments: params ?? {} }, signal);
        const content = toPiContent(result);
        if (result?.isError) {
          throw new Error(content.map((part) => (part.type === "text" ? part.text : "")).join("\\n") || "MCP tool error");
        }
        return { content, details: { mcpServer: SERVER.name, mcpTool: tool.name, structuredContent: result?.structuredContent } };
      },
    });
    registered.set(name, tool.name);
    return name;
  }

  async function syncTools() {
    const tools = await listTools();
    const current = new Set();
    const added = [];
    for (const tool of tools) {
      if (HIDDEN_TOOLS.includes(tool.name)) continue;
      const name = piToolName(tool.name);
      current.add(name);
      if (!registered.has(name)) added.push(name);
      registerMcpTool(tool);
    }
    const removed = [...registered.keys()].filter((name) => !current.has(name));
    for (const name of removed) registered.delete(name);
    if (added.length > 0 || removed.length > 0) {
      const active = new Set(pi.getActiveTools());
      for (const name of added) active.add(name);
      for (const name of removed) active.delete(name);
      pi.setActiveTools([...active]);
    }
  }

  pi.on("session_start", async (_event, ctx) => {
    if (client) return;
    try {
      client = createClient(ctx.cwd, () => {
        syncTools().catch((error) => ctx.ui.notify("Resin tools refresh failed: " + error.message, "warning"));
      });
      await withTimeout(
        client.request("initialize", {
          protocolVersion: PROTOCOL_VERSION,
          capabilities: {},
          clientInfo: { name: "resin-pi-bridge", version: "1" },
        }),
        CONNECT_TIMEOUT_MS,
        SERVER.name + " MCP initialize",
      );
      client.notify("notifications/initialized", {});
      await withTimeout(syncTools(), CONNECT_TIMEOUT_MS, SERVER.name + " MCP tools/list");
    } catch (error) {
      client?.close();
      client = null;
      ctx.ui.notify("Resin MCP bridge unavailable: " + error.message, "warning");
    }
  });

  pi.on("session_shutdown", () => {
    client?.close();
    client = null;
  });
}
`;
}
